version: '3.3'

services:
  backend:
    container_name: compliance-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - compliance-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    container_name: compliance-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - compliance-network
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0

networks:
  compliance-network:
    driver: bridge