version: '3.3'

services:
  backend:
    container_name: compliance-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - compliance-network

  frontend:
    container_name: compliance-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - compliance-network
    environment:
      - NODE_ENV=production

  nginx:
    container_name: compliance-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - compliance-network

networks:
  compliance-network:
    driver: bridge