version: '3.3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VIRTUAL_HOST=reporter.dawood.design
      - LETSENCRYPT_HOST=reporter.dawood.design
    restart: always
    networks:
      - proxy-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=reporter.dawood.design
      - LETSENCRYPT_HOST=reporter.dawood.design
      - VIRTUAL_PATH=/
    restart: always
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true